#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015 Juca Crispim <juca@poraodojuca.net>

# This file is part of toxicbuild.

# toxicbuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# toxicbuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with toxicbuild. If not, see <http://www.gnu.org/licenses/>.


import os
import sys
from mando import command, main
from pyrocumulus.commands.base import get_command


@command
def start(workdir, daemonize=False, stdout='/dev/null', stderr='/dev/null',
          pidfile=None, loglevel='info'):
    """ Starts the web interface.

    Starts the build server to listen on the specified port for
    requests from addr (0.0.0.0 means everyone). Addr and port params
    came from the configfile

    :param workdir: Work directory for server.
    :param --daemonize: Run as daemon. Defaults to False
    :param --stdout: stdout path. Defaults to /dev/null
    :param --stderr: stderr path. Defaults to /dev/null
    :param --pidfile: pid file for the process.
    :param --loglevel: Level for logging messages. Defaults to `info`.
    """

    workdir = os.path.abspath(workdir)
    os.chdir(workdir)
    sys.path.append(workdir)

    os.environ['TOXICUI_SETTINGS'] = os.path.join(workdir,
                                                  'toxicweb_settings.py')
    os.environ['PYROCUMULUS_SETTINGS_MODULE'] = 'toxicweb_settings'
    from toxicbuild.ui import settings

    sys.argv = ['pyromanager.py', 'web']
    command = get_command('runtornado')()
    command.kill = False
    command.daemonize = daemonize
    command.stderr = stderr
    command.stdout = stdout
    command.port = settings.TORNADO_PORT
    command.pidfile = pidfile
    command.run()


def stop(workdir, pidfile=None):
    """ Stops the web interface.

    :param workdir: Work directory for the ui to be killed.
    :param --pidfile: pid file for the process.
    """

    workdir = os.path.abspath(workdir)
    os.chdir(workdir)
    sys.path.append(workdir)

    os.environ['TOXICUI_SETTINGS'] = os.path.join(workdir,
                                                  'toxicweb_settings.py')
    os.environ['PYROCUMULUS_SETTINGS_MODULE'] = 'toxicweb_settings'
    command = get_command('runtornado')()
    command.pidfile = pidfile
    command.kill = True
    command.run()


if __name__ == '__main__':
    main()
