#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015 Juca Crispim <juca@poraodojuca.net>

# This file is part of toxicbuild.

# toxicbuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# toxicbuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with toxicbuild. If not, see <http://www.gnu.org/licenses/>.


import os
import pkg_resources
import shutil
import sys
from mando import command, main
from tornado.platform.asyncio import AsyncIOMainLoop
from pyrocumulus.commands.base import get_command

# we install the asyncio loop for tornado so we can
# use it inside tornado handlers with @gen.coroutine
AsyncIOMainLoop().install()


@command
def start(workdir, daemonize=False, stdout='/dev/null', stderr='/dev/null',
          pidfile=None, loglevel='info'):
    """ Starts the web interface.

    Starts the build server to listen on the specified port for
    requests from addr (0.0.0.0 means everyone). Addr and port params
    came from the configfile

    :param workdir: Work directory for server.
    :param --daemonize: Run as daemon. Defaults to False
    :param --stdout: stdout path. Defaults to /dev/null
    :param --stderr: stderr path. Defaults to /dev/null
    :param --pidfile: pid file for the process.
    :param --loglevel: Level for logging messages. Defaults to `info`.
    """

    workdir = os.path.abspath(workdir)
    os.chdir(workdir)
    sys.path.append(workdir)

    os.environ['TOXICUI_SETTINGS'] = os.path.join(workdir,
                                                  'toxicui.conf')
    os.environ['PYROCUMULUS_SETTINGS_MODULE'] = 'toxicui'
    from toxicbuild.ui import settings

    sys.argv = ['pyromanager.py', 'web']
    command = get_command('runtornado')()
    command.kill = False
    command.daemonize = daemonize
    command.stderr = stderr
    command.stdout = stdout
    command.port = settings.TORNADO_PORT
    command.pidfile = pidfile
    command.run()


@command
def stop(workdir, pidfile=None):
    """ Stops the web interface.

    :param workdir: Work directory for the ui to be killed.
    :param --pidfile: pid file for the process.
    """

    workdir = os.path.abspath(workdir)
    os.chdir(workdir)
    sys.path.append(workdir)

    os.environ['TOXICUI_SETTINGS'] = os.path.join(workdir,
                                                  'toxicui.conf')
    os.environ['PYROCUMULUS_SETTINGS_MODULE'] = 'toxicui'
    command = get_command('runtornado')()
    command.pidfile = pidfile
    command.kill = True
    command.run()


@command
def create(root_dir):
    """ Create a new toxicweb project.

    :param --root_dir: Root directory for toxicweb.
    """
    print('Creating root_dir {}'.format(root_dir))

    os.mkdir(root_dir)

    fakesettings = os.path.join(root_dir, 'fakesettings.py')
    with open(fakesettings, 'w') as f:
        f.write('DATABASE = {}')
    os.environ['TOXICUI_SETTINGS'] = fakesettings

    template_fname = 'toxicweb_settings.py.tmpl'
    template_dir = pkg_resources.resource_filename('toxicbuild.ui',
                                                   'templates')
    template_file = os.path.join(template_dir, template_fname)
    dest_file = os.path.join(root_dir, 'toxicweb_settings.py')
    shutil.copyfile(template_file, dest_file)
    os.remove(fakesettings)

if __name__ == '__main__':
    main()
