#!/usr/bin/env python
#-*- coding: utf-8 -*-



# Copyright 2015 Juca Crispim <juca@poraodojuca.net>

# This file is part of toxicbuild.

# toxicbuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# toxicbuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with toxicbuild. If not, see <http://www.gnu.org/licenses/>.

import os
from mando import command, main
from toxicbuild.core.utils import daemonize as daemon
from toxicbuild.slave import server


@command
def runserver(workdir, addr='0.0.0.0', port=7777, daemonize=False,
              stdout='/dev/null', stderr='/dev/null'):
    """ Starts the build server.

    Starts the build server on the listen on the specified port for
    requests from addr (0.0.0.0 means everyone).

    :param workdir: Work directory for server.
    :param -a, --addr: IP address to accept requests from. Defaults to 0.0.0.0
    :param -p, --port: Port to listen.
    :param --daemonize: Run as daemon.
    :param --stdout: stdout path. Defaults to /dev/null
    :param --stderr: stderr path. Defaults to /dev/null
    """

    if daemonize:
        pidfile = 'toxicslave{}.pid'.format(port)
        daemon(call=server.run_server, cargs=(addr, port), ckwargs={},
               stdout=stdout, stderr=stderr, workdir=workdir, pidfile=pidfile)
    else:
        os.chdir(workdir)
        server.run_server(addr, port)


if __name__ == '__main__':
    main()
