#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015 Juca Crispim <juca@poraodojuca.net>

# This file is part of toxicbuild.

# toxicbuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# toxicbuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with toxicbuild. If not, see <http://www.gnu.org/licenses/>.


# No comments here, sir. Let's do some mess around.

import os


cf = os.path.join(os.path.join(
    os.path.expanduser('~'), '.toxicui'), 'toxicui.conf')
if not os.path.exists(cf):
    try:
        os.mkdir(os.path.dirname(cf))
    except:
        pass

    with open(cf, 'w') as fd:
        fd.write('# toxicbuild ui conffile')

os.environ['TOXICUI_SETTINGS'] = cf

if __name__ == '__main__':

    import sys
    from toxicbuild.ui.cli import ToxicCli

    if '-h' in sys.argv or '--help' in sys.argv:
        print('nice try.')
        sys.exit(1)

    try:
        host, port, token = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    except IndexError:
        print('params missing')
        sys.exit(1)

    tc = ToxicCli(host, port, token)
    tc.run()
