#!/usr/bin/env python
#-*- coding: utf-8 -*-

# Copyright 2015 Juca Crispim <juca@poraodojuca.net>

# This file is part of toxicbuild.

# toxicbuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# toxicbuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with toxicbuild. If not, see <http://www.gnu.org/licenses/>.

import os
from mando import command, main
from toxicbuild.core.utils import daemonize as daemon

PIDFILE = 'toxicslave.pid'


@command
def start(workdir, daemonize=False, stdout='/dev/null', stderr='/dev/null',
          conffile=None):
    """ Starts the build server.

    Starts the build server to listen on the specified port for
    requests from addr (0.0.0.0 means everyone). Addr and port params
    came from the configfile

    :param workdir: Work directory for server.
    :param --daemonize: Run as daemon. Defaults to False
    :param --stdout: stdout path. Defaults to /dev/null
    :param --stderr: stderr path. Defaults to /dev/null
    :param -c, --conffile: path to config file. Defaults to None.
      If not conffile, will look for a file called ``toxicslave.conf``
      inside ``workdir``
    """

    if conffile:
        os.environ['TOXICSLAVE_SETTINGS'] = conffile

    # These toxicbuild.slave imports must be here so I can
    # change the settings file before settings are instanciated.
    from toxicbuild.slave import server, settings

    addr = settings.ADDR
    port = settings.PORT

    if daemonize:
        daemon(call=server.run_server, cargs=(addr, port), ckwargs={},
               stdout=stdout, stderr=stderr, workdir=workdir, pidfile=PIDFILE)
    else:
        os.chdir(workdir)
        server.run_server(addr, port)


@command
def stop(workdir):
    """ Stops a buid server instance.

    :param workdir: Workdir for master to be killed. Looks for a file
      ``toxicslave.pid`` inside ``workdir``.
    """

    os.chdir(workdir)
    with open(PIDFILE) as fd:
        pid = int(fd.read())

    os.kill(pid, 9)
    os.remove(PIDFILE)


if __name__ == '__main__':
    main()
