FROM debian:buster-slim


RUN apt-get update && apt-get install -y sudo curl make gcc
RUN curl -O https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz

RUN tar -C /usr/local -xzf go1.14.2.linux-amd64.tar.gz
ENV PATH="$PATH:/usr/local/go/bin"
RUN rm go1.14.2.linux-amd64.tar.gz

# See https://github.com/debuerreotype/debuerreotype/issues/10
RUN mkdir -p /usr/share/man/man1
RUN mkdir -p /usr/share/man/man2
RUN mkdir -p /usr/share/man/man3
RUN mkdir -p /usr/share/man/man4
RUN mkdir -p /usr/share/man/man5
RUN mkdir -p /usr/share/man/man6
RUN mkdir -p /usr/share/man/man7
RUN mkdir -p /usr/share/man/man8

RUN echo "exit 0" > /usr/sbin/policy-rc.d

COPY sudoers /etc/sudoers
RUN useradd -ms /bin/bash toxicuser
RUN addgroup toxicuser sudo
USER toxicuser
WORKDIR /home/toxicuser
