FROM python:3.7.4-slim-buster

RUN apt-get update && apt-get install -y chromium-driver xvfb git-crypt sudo git

COPY conf/sudoers /etc/sudoers
RUN useradd -ms /bin/bash toxicuser
RUN addgroup toxicuser sudo
USER toxicuser
WORKDIR /home/toxicuser


# create a virtualenv
RUN python3.7 -m venv /home/toxicuser/.toxic-venv
ENV PATH="/home/toxicuser/.toxic-venv/bin:$PATH"

# The ideia here is to install the dependencies only if the requirements
# file has changed. So first we copy only it and install the deps.
RUN mkdir -p /home/toxicuser/.toxic-venv/src/toxicbuild
COPY dist/toxicbuild/requirements.txt /home/toxicuser/.toxic-venv/src/toxicbuild
WORKDIR /home/toxicuser/.toxic-venv/src/toxicbuild
RUN pip install -r requirements.txt
RUN rm /home/toxicuser/.toxic-venv/src/toxicbuild/requirements.txt

# After the deps are installed we copy the source files
COPY dist/ /tmp/src/
RUN cp -r /tmp/src/* /home/toxicuser/.toxic-venv/src/
RUN chown -R toxicuser:toxicuser /home/toxicuser/.toxic-venv/src/

RUN sudo rm -rf /tmp/src/

COPY test-dist/ /tmp/src/
RUN cp -r /tmp/src/* /home/toxicuser/.toxic-venv/src/toxicbuild
RUN chown -R toxicuser:toxicuser /home/toxicuser/.toxic-venv/src/
