version: '2'
services:

  web:
    image: toxicweb:latest
    env_file: web.env
    ports:
      - "8888:8888"

    environment:
      HOLE_HOST: master

    depends_on:
      - master

  slave:
    image: toxicslave:latest
    env_file: ./slave.env

  output:
    image: toxicoutput:latest
    env_file: ./output.env

    depends_on:
      - rabbitmq
      - mongo

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq

  scheduler:
    image: toxicscheduler:latest
    env_file: ./master.env

    environment:
       AMQPHOST: rabbitmq
       DBHOST: mongo
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - rabbitmq
      - mongo
      - zookeeper

  poller:
    image: toxicpoller:latest
    env_file: ./master.env

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - rabbitmq
      - mongo
      - zookeeper

  integrations:
    image: toxicintegrations:latest
    env_file: ./integrations.env
    ports:
      - "9999:9999"

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"
       NOTIFICATIONS_API_URL: "http://output:9432/"

  master:
    image: toxicmaster:latest
    env_file: ./master.env

    depends_on:
      - rabbitmq
      - mongo
      - zookeeper
      - output
      - poller
      - scheduler
      - integrations
      - slave

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"
       NOTIFICATIONS_API_URL: "http://output:9432/"

  create_slave_token:
    image: toxicslave:latest
    command: toxicslave create_token /home/toxicuser/ci/slave/toxicslave.conf --show-encrypted

  create_output_token:
    image: toxicoutput:latest
    command: toxicoutput create_token /home/toxicuser/ci/output

    depends_on:
      - mongo

    environment:
       DBHOST: mongo

  create_master_token:
    image: toxicmaster:latest
    command: toxicmaster create_token /home/toxicuser/ci/master/toxicmaster.conf --show-encrypted

    depends_on:
      - mongo

  create_user:
    image: toxicmaster:latest
    command: toxicmaster create_user /home/toxicuser/ci/master/toxicmaster.conf --email $TOXICMASTER_USER_EMAIL --password $TOXICMASTER_USER_PASSWORD --superuser

    depends_on:
      - mongo

    environment:
       DBHOST: mongo

  add_slave:
    image: toxicmaster:latest
    command: toxicmaster add_slave /home/toxicuser/ci/master/toxicmaster.conf localslave slave 7777 $SLAVE_ACCESS_TOKEN $SLAVE_OWNER_ID

    depends_on:
      - mongo

    environment:
       DBHOST: mongo

  setup-env:
    image: toxictest

    depends_on:
      - mongo
      - zookeeper
      - rabbitmq

  pylint:
    image: toxictest
    command: bash ./build-scripts/run_linter.sh

  pep8:
    image: toxictest
    command: bash ./build-scripts/check_style.sh

  xenon:
    image: toxictest
    command: xenon -e "toxicbuild/master/locks.py" toxicbuild -b B

  unit-tests:
    image: toxictest
    command: ./build-scripts/check_coverage.sh toxicbuild 100

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - mongo
      - zookeeper
      - rabbitmq

  functional-tests:
    image: toxictest
    command: python setup.py test --test-suite=tests.functional

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - mongo
      - zookeeper
      - rabbitmq

  js-unit-tests:
    image: toxictest-selenium
    command: ./build-scripts/run_jasmine_tests.sh

  selenium-tests:
    image: toxictest-selenium
    command: ./build-scripts/run_selenium_tests.sh

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - mongo
      - zookeeper
      - rabbitmq

  selenium-integration-tests:
    image: toxictest-selenium
    command: ./build-scripts/run_integration_tests.sh

    environment:
       DBHOST: mongo
       AMQPHOST: rabbitmq
       ZK_SERVERS: "zookeeper:2181"

    depends_on:
      - mongo
      - zookeeper
      - rabbitmq


  mongo:
    image: mongo:4.0
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: always

  zookeeper:
    image: zookeeper:3.5
    restart: always
