# Here we simply install selenium and copy the source files
FROM toxictestbase

USER root

RUN apt-get update && apt-get install -y chromium-driver xvfb git-crypt

COPY dist/ /tmp/src/
RUN cp -r /tmp/src/* /home/toxicuser/.toxic-venv/src/
RUN chown -R toxicuser:toxicuser /home/toxicuser/.toxic-venv/src/
RUN rm -rf /tmp/src/

COPY test-dist/ /tmp/src/
RUN cp -r /tmp/src/* /home/toxicuser/.toxic-venv/src/toxicbuild
RUN cp -r /tmp/src/* /home/toxicuser/.toxic-venv/src/toxicbuild
RUN chown -R toxicuser:toxicuser /home/toxicuser/.toxic-venv/src/
RUN rm -rf /tmp/src/

USER toxicuser
