# In this dockerfile we install de runtime dependencies and create
# a normal user
FROM python:3.11.3-slim-bullseye

RUN apt-get update && apt-get install -y git libyaml-dev locales
RUN sed -i '/^#.* en_US.* /s/^#//' /etc/locale.gen
RUN sed -i '/^#.* pt_BR.* /s/^#//' /etc/locale.gen
RUN locale-gen

RUN useradd -ms /bin/bash toxicuser

USER toxicuser
WORKDIR /home/toxicuser

# create a virtualenv
RUN python3.11 -m venv /home/toxicuser/.toxic-venv
ENV PATH="/home/toxicuser/.toxic-venv/bin:$PATH"

# The ideia here is to install the dependencies only if the setup.py
# file has changed. So first we copy only it and install the deps.
RUN mkdir -p /home/toxicuser/.toxic-venv/src/toxicbuild/toxicbuild
COPY dist/toxicbuild/toxicbuild/__init__.py /home/toxicuser/.toxic-venv/src/toxicbuild/toxicbuild
COPY dist/toxicbuild/README /home/toxicuser/.toxic-venv/src/toxicbuild
COPY dist/toxicbuild/setup.py /home/toxicuser/.toxic-venv/src/toxicbuild
WORKDIR /home/toxicuser/.toxic-venv/src/toxicbuild
# Install the runtime dependencies
RUN pip install -e .

# Uninstall the code (unlink from site-packages) so we can use the 'real' code
# in the test image
RUN pip uninstall -y toxicbuild
